/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react/jsx-no-target-blank */
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Brick Wall Security</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <nav
          className='navbar navbar-expand-lg navbar-light fixed-top shadow-sm'
          id='mainNav'
        >
          <div className='container px-5'>
            <a className='navbar-brand fw-bold' href='#page-top'>
              <Image
                src='/LOGO/pngs/main logo.png'
                alt='Brickwall Security Logo'
                width={400}
                height={50}
              />
            </a>
            <button
              className='navbar-toggler'
              type='button'
              data-bs-toggle='collapse'
              data-bs-target='#navbarResponsive'
              aria-controls='navbarResponsive'
              aria-expanded='false'
              aria-label='Toggle navigation'
            >
              Menu
              <i className='bi-list' />
            </button>
            <div className='collapse navbar-collapse' id='navbarResponsive'>
              <ul className='navbar-nav ms-auto me-4 my-3 my-lg-0'>
                <li className='nav-item'>
                  <a className='nav-link me-lg-3' href='#features'>
                    Features
                  </a>
                </li>
                <li className='nav-item'>
                  <a className='nav-link me-lg-3' href='#download'>
                    Download
                  </a>
                </li>
              </ul>
              <button
                className='btn btn-primary rounded-pill px-3 mb-2 mb-lg-0'
                data-bs-toggle='modal'
                data-bs-target='#feedbackModal'
              >
                <span className='d-flex align-items-center'>
                  <i className='bi-chat-text-fill me-2' />
                  <span className='small'>Send Feedback</span>
                </span>
              </button>
            </div>
          </div>
        </nav>
        {/* Mashead header*/}
        <header className='masthead'>
          <div className='container px-5'>
            <div className='row gx-5 align-items-center'>
              <div className='col-lg-6'>
                {/* Mashead text and app badges*/}
                <div className='mb-5 mb-lg-0 text-center text-lg-start'>
                  <h1 className='display-1 lh-1 mb-3'>Brickwall Security</h1>
                  <p className='lead fw-normal text-muted mb-5'>
                    Your Cybersecurity Shield in an Evolving Digital Landscape
                  </p>
                </div>
              </div>
              <div className='col-lg-6'>
                {/* Masthead device mockup feature*/}
                <div className='masthead-device-mockup'>
                  <svg
                    className='circle'
                    viewBox='0 0 100 100'
                    xmlns='http://www.w3.org/2000/svg'
                  >
                    <defs>
                      <linearGradient
                        id='circleGradient'
                        gradientTransform='rotate(45)'
                      >
                        <stop className='gradient-start-color' offset='0%' />
                        <stop className='gradient-end-color' offset='100%' />
                      </linearGradient>
                    </defs>
                    <circle cx={50} cy={50} r={50} />
                  </svg>
                  <svg
                    className='shape-1 d-none d-sm-block'
                    viewBox='0 0 240.83 240.83'
                    xmlns='http://www.w3.org/2000/svg'
                  >
                    <rect
                      x='-32.54'
                      y='78.39'
                      width='305.92'
                      height='84.05'
                      rx='42.03'
                      transform='translate(120.42 -49.88) rotate(45)'
                    />
                    <rect
                      x='-32.54'
                      y='78.39'
                      width='305.92'
                      height='84.05'
                      rx='42.03'
                      transform='translate(-49.88 120.42) rotate(-45)'
                    />
                  </svg>
                  <svg
                    className='shape-2 d-none d-sm-block'
                    viewBox='0 0 100 100'
                    xmlns='http://www.w3.org/2000/svg'
                  >
                    <circle cx={50} cy={50} r={50} />
                  </svg>
                  <div className='device-wrapper'>
                    <div
                      className='device'
                      data-device='iPhoneX'
                      data-orientation='portrait'
                      data-color='black'
                    >
                      <div className='screen bg-black'>
                        {/* PUT CONTENTS HERE:*/}
                        {/* * * This can be a video, image, or just about anything else.*/}
                        {/* * * Set the max width of your media to 100% and the height to*/}
                        {/* * * 100% like the demo example below.*/}
                        <video
                          muted='muted'
                          autoPlay=''
                          loop=''
                          style={{ maxWidth: '100%', height: '100%' }}
                        >
                          <source
                            src='assets/img/demo-screen.mp4'
                            type='video/mp4'
                          />
                        </video>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </header>
        {/* Quote/testimonial aside*/}
        <aside className='text-center bg-gradient-primary-to-secondary'>
          <div className='container px-5'>
            <div className='row gx-5 justify-content-center'>
              <div className='col-xl-8'>
                <div className='h2 fs-1 text-white mb-4'>
                  Welcome to Brickwall Security, where we transform the
                  complexity of cybersecurity into your ultimate digital
                  defense. In an age where threats are ever-evolving, our
                  comprehensive suite of services ensures your business stays
                  one step ahead. From 24/7 monitoring to incident response,
                  from threat intelligence to specialized security training, we
                  provide robust, tailor-made solutions for your peace of mind.
                  With Brickwall Security, navigate the digital landscape with
                  confidence and resilience.
                </div>
                <img
                  src='assets/img/tnw-logo.svg'
                  alt='...'
                  style={{ height: '3rem' }}
                />
              </div>
            </div>
          </div>
        </aside>
        {/* App features section */}
        <section id='features'>
          <div className='container px-5'>
            <div className='row gx-5 align-items-center'>
              <div className='col-lg-8 order-lg-1 mb-5 mb-lg-0'>
                <div className='container-fluid px-5'>
                  <div className='row gx-5'>
                    <div className='col-md-6 mb-5'>
                      {/* Feature item*/}
                      <div className='text-center'>
                        <i className='bi-phone icon-feature text-gradient d-block mb-3' />
                        <h3 className='font-alt'>
                          Managed Security Operation Center (SOC) as a Service
                        </h3>
                        <p className='text-muted mb-0'>
                          We offer 24/7 proactive monitoring and analysis of
                          your security events. Our SOC team is ready to respond
                          to any detected threats, providing guidance for
                          effective mitigation and remediation.
                        </p>
                      </div>
                    </div>
                    <div className='col-md-6 mb-5'>
                      {/* Feature item*/}
                      <div className='text-center'>
                        <i className='bi-camera icon-feature text-gradient d-block mb-3' />
                        <h3 className='font-alt'>
                          Digital Forensics and Incident Response (DFIR)
                        </h3>
                        <p className='text-muted mb-0'>
                          Our dedicated incident response team assists with
                          swift and effective response to security incidents,
                          offering expert support and guidance to ensure a quick
                          recovery and minimal disruption to your business.
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className='row'>
                    <div className='col-md-6 mb-5 mb-md-0'>
                      {/* Feature item*/}
                      <div className='text-center'>
                        <i className='bi-gift icon-feature text-gradient d-block mb-3' />
                        <h3 className='font-alt'>
                          Threat Intelligence and Threat Hunting
                        </h3>
                        <p className='text-muted mb-0'>
                          We provide both real-time and historical threat
                          investigation, helping you understand your potential
                          threats and implement the most effective security
                          measures to protect your valuable assets
                        </p>
                      </div>
                    </div>
                    <div className='col-md-6'>
                      {/* Feature item*/}
                      <div className='text-center'>
                        <i className='bi-patch-check icon-feature text-gradient d-block mb-3' />
                        <h3 className='font-alt'>
                          Security Training and Awareness
                        </h3>
                        <p className='text-muted mb-0'>
                          We offer a comprehensive range of cybersecurity
                          training services, designed to educate your staff
                          about the importance of cybersecurity and the best
                          practices to maintain a secure working environment.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className='col-lg-4 order-lg-0'>
                {/* Features section device mockup*/}
                <div className='features-device-mockup'>
                  <svg
                    className='circle'
                    viewBox='0 0 100 100'
                    xmlns='http://www.w3.org/2000/svg'
                  >
                    <defs>
                      <linearGradient
                        id='circleGradient'
                        gradientTransform='rotate(45)'
                      >
                        <stop className='gradient-start-color' offset='0%' />
                        <stop className='gradient-end-color' offset='100%' />
                      </linearGradient>
                    </defs>
                    <circle cx={50} cy={50} r={50} />
                  </svg>
                  <svg
                    className='shape-1 d-none d-sm-block'
                    viewBox='0 0 240.83 240.83'
                    xmlns='http://www.w3.org/2000/svg'
                  >
                    <rect
                      x='-32.54'
                      y='78.39'
                      width='305.92'
                      height='84.05'
                      rx='42.03'
                      transform='translate(120.42 -49.88) rotate(45)'
                    />
                    <rect
                      x='-32.54'
                      y='78.39'
                      width='305.92'
                      height='84.05'
                      rx='42.03'
                      transform='translate(-49.88 120.42) rotate(-45)'
                    />
                  </svg>
                  <svg
                    className='shape-2 d-none d-sm-block'
                    viewBox='0 0 100 100'
                    xmlns='http://www.w3.org/2000/svg'
                  >
                    <circle cx={50} cy={50} r={50} />
                  </svg>
                  <div className='device-wrapper'>
                    <div
                      className='device'
                      data-device='iPhoneX'
                      data-orientation='portrait'
                      data-color='black'
                    >
                      <div className='screen bg-black'>
                        {/* PUT CONTENTS HERE:*/}
                        {/* * * This can be a video, image, or just about anything else.*/}
                        {/* * * Set the max width of your media to 100% and the height to*/}
                        {/* * * 100% like the demo example below.*/}
                        <video
                          muted='muted'
                          autoPlay=''
                          loop=''
                          style={{ maxWidth: '100%', height: '100%' }}
                        >
                          <source
                            src='assets/img/demo-screen.mp4'
                            type='video/mp4'
                          />
                        </video>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* Basic features section*/}
        <section className='bg-light'>
          <div className='container px-5'>
            <div className='row gx-5 align-items-center justify-content-center justify-content-lg-between'>
              <div className='col-12 col-lg-5'>
                <h2 className='display-4 lh-1 mb-4'>
                  Secure Your Digital Future with Brickwall Security Today!
                </h2>
                <p className='lead fw-normal text-muted mb-5 mb-lg-0'>
                  Don't leave your cybersecurity to chance. Secure your business
                  with Brickwall Security today! In an ever-evolving digital
                  landscape, staying one step ahead is crucial. With our suite
                  of comprehensive services, we offer the robust, tailor-made
                  solutions that your business needs to thrive safely and
                  confidently. Get in touch with us today and let's fortify your
                  digital world together.
                </p>
              </div>
              <div className='col-sm-8 col-md-6'>
                <div className='px-5 px-sm-0'>
                  <img
                    className='img-fluid rounded-circle'
                    src='https://source.unsplash.com/u8Jn2rzYIps/900x900'
                    alt='...'
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* Call to action section*/}
        <section className='cta'>
          <div className='cta-content'>
            <div className='container px-5'>
              <h2 className='text-white display-1 lh-1 mb-4'>
                Brickwall Security:
                <br />
                Guarding Your Digital Domain.
              </h2>
              <a
                className='btn btn-outline-light py-3 px-4 rounded-pill'
                href='https://startbootstrap.com/theme/new-age'
                target='_blank'
              >
                Contact Us Now
              </a>
            </div>
          </div>
        </section>

        {/* Footer*/}
        <footer className='bg-black text-center py-5'>
          <div className='container px-5'>
            <div className='text-white-50 small'>
              <div className='mb-2'>
                © BrickWall Security 2023. All Rights Reserved.
              </div>
              <a href='#!'>Privacy</a>
              <span className='mx-1'>·</span>
              <a href='#!'>Terms</a>
              <span className='mx-1'>·</span>
              <a href='#!'>FAQ</a>
            </div>
          </div>
        </footer>
        {/* Feedback Modal*/}
        <div
          className='modal fade'
          id='feedbackModal'
          tabIndex={-1}
          aria-labelledby='feedbackModalLabel'
          aria-hidden='true'
        >
          <div className='modal-dialog modal-dialog-centered'>
            <div className='modal-content'>
              <div className='modal-header bg-gradient-primary-to-secondary p-4'>
                <h5
                  className='modal-title font-alt text-white'
                  id='feedbackModalLabel'
                >
                  Send feedback
                </h5>
                <button
                  className='btn-close btn-close-white'
                  type='button'
                  data-bs-dismiss='modal'
                  aria-label='Close'
                />
              </div>
              <div className='modal-body border-0 p-4'>
                {/* * * * * * * * * * * * * * * **/}
                {/* * * SB Forms Contact Form * **/}
                {/* * * * * * * * * * * * * * * **/}
                {/* This form is pre-integrated with SB Forms.*/}
                {/* To make this form functional, sign up at*/}
                {/* https://startbootstrap.com/solution/contact-forms*/}
                {/* to get an API token!*/}
                <form id='contactForm' data-sb-form-api-token='API_TOKEN'>
                  {/* Name input*/}
                  <div className='form-floating mb-3'>
                    <input
                      className='form-control'
                      id='name'
                      type='text'
                      placeholder='Enter your name...'
                      data-sb-validations='required'
                    />
                    <label htmlFor='name'>Full name</label>
                    <div
                      className='invalid-feedback'
                      data-sb-feedback='name:required'
                    >
                      A name is required.
                    </div>
                  </div>
                  {/* Email address input*/}
                  <div className='form-floating mb-3'>
                    <input
                      className='form-control'
                      id='email'
                      type='email'
                      placeholder='name@example.com'
                      data-sb-validations='required,email'
                    />
                    <label htmlFor='email'>Email address</label>
                    <div
                      className='invalid-feedback'
                      data-sb-feedback='email:required'
                    >
                      An email is required.
                    </div>
                    <div
                      className='invalid-feedback'
                      data-sb-feedback='email:email'
                    >
                      Email is not valid.
                    </div>
                  </div>
                  {/* Phone number input*/}
                  <div className='form-floating mb-3'>
                    <input
                      className='form-control'
                      id='phone'
                      type='tel'
                      placeholder='(123) 456-7890'
                      data-sb-validations='required'
                    />
                    <label htmlFor='phone'>Phone number</label>
                    <div
                      className='invalid-feedback'
                      data-sb-feedback='phone:required'
                    >
                      A phone number is required.
                    </div>
                  </div>
                  {/* Message input*/}
                  <div className='form-floating mb-3'>
                    <textarea
                      className='form-control'
                      id='message'
                      type='text'
                      placeholder='Enter your message here...'
                      style={{ height: '10rem' }}
                      data-sb-validations='required'
                      defaultValue={''}
                    />
                    <label htmlFor='message'>Message</label>
                    <div
                      className='invalid-feedback'
                      data-sb-feedback='message:required'
                    >
                      A message is required.
                    </div>
                  </div>
                  {/* Submit success message*/}
                  {/**/}
                  {/* This is what your users will see when the form*/}
                  {/* has successfully submitted*/}
                  <div className='d-none' id='submitSuccessMessage'>
                    <div className='text-center mb-3'>
                      <div className='fw-bolder'>
                        Form submission successful!
                      </div>
                      To activate this form, sign up at
                      <br />
                      <a href='https://startbootstrap.com/solution/contact-forms'>
                        https://startbootstrap.com/solution/contact-forms
                      </a>
                    </div>
                  </div>
                  {/* Submit error message*/}
                  {/**/}
                  {/* This is what your users will see when there is*/}
                  {/* an error submitting the form*/}
                  <div className='d-none' id='submitErrorMessage'>
                    <div className='text-center text-danger mb-3'>
                      Error sending message!
                    </div>
                  </div>
                  {/* Submit Button*/}
                  <div className='d-grid'>
                    <button
                      className='btn btn-primary rounded-pill btn-lg disabled'
                      id='submitButton'
                      type='submit'
                    >
                      Submit
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </>
    </>
  )
}
